### ISSUE TITLE
Windows Defender scans (downloaded) EF Bundle as a Trojan

### ISSUE THREAD

**Issue by bartlannoeye** [aspnet/EntityFrameworkCore#33294]
## File a bug

I was troubleshooting why EF Bundle did not deploy in one of my teams's Azure DevOps pipelines and thought to quickly download the build artifact to see if it was a Azure DevOps issue or a bundle file issue.

After downloading (both as exe and extracting as zipped root folder), I got a notification from Windows Defender.

<img width="257" alt="image" src="https://github.com/dotnet/efcore/assets/5115577/bbfa1067-5dfd-41dd-8f94-e25723e26071">

Since building local does work, this issue is certainly not critical but I find it very interesting and worth some research.

### Include your code
Build agent image: 
``` yaml
pool:
  vmImage: 'windows-latest'
```

Bundle task in build pipeline

``` yaml
  - task: DotNetCoreCLI@2
    displayName: 'Install Dotnet EF Tool'
    inputs:
      command: custom
      custom: "tool"
      arguments: "install --global dotnet-ef"

  - task: DotNetCoreCLI@2
    displayName: EFBundle
    inputs:
      command: custom
      custom: 'ef '
      arguments: 'migrations bundle --self-contained --project "src/Infrastructure/Infrastructure.csproj" --startup-project "src/Api/Api.csproj" -r win-x64 -o $(Build.ArtifactStagingDirectory)/SQL/Bundle.exe --verbose'
```
